name: pramujadi
favicon: null
layout_spectrum: 0.8515704348683357
typography_spectrum: 0.8767109403852373
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2972612869925797
  lightness: 0.7753501322586089
  saturation: 0.5493980208411813
  rhythmicContrast: 0.7636880215723068
purpose: []
